CREATE TABLE `CLIENTE` (
  `CLIENTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLIENTE_NOMBRE` varchar(180) NOT NULL,
  `CLIENTE_DIRECCION` varchar(250) NOT NULL,
  `CLIENTE_DNI` varchar(8) DEFAULT NULL,
  `CLIENTE_RUC` varchar(12) DEFAULT NULL,
  `CLIENTE_TELEFONO` varchar(12) DEFAULT NULL,
  `CLIENTE_ESTADO` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`CLIENTE_ID`),
  UNIQUE KEY `CLIENTE_DNI` (`CLIENTE_DNI`),
  UNIQUE KEY `CLIENTE_RUC` (`CLIENTE_RUC`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=latin1;

CREATE TABLE `EMPLEADO` (
  `EMPLEADO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPLEADO_DNI` varchar(8) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLEADO_NOMBRES` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLEADO_APATERNO` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLEADO_AMATERNO` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `EMPLEADO_CORREO` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EMPLEADO_IMAGEN` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EMPLEADO_TELEFONO` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EMPLEADO_ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`EMPLEADO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `INVENTARIO` (
  `INVENTARIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) NOT NULL,
  `INVENTARIO_CODIGO_BARRA` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `INVENTARIO_UBICACION` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `INVENTARIO_LOTE` int(11) DEFAULT NULL,
  `INVENTARIO_CANTIDAD` int(11) NOT NULL,
  `INVENTARIO_FECHA_INGRESO` datetime NOT NULL,
  `INVENTARIO_FECHA_FABRICACION` date NOT NULL,
  `INVENTARIO_FECHA_VENCIMIENTO` date NOT NULL,
  `INVENTARIO_ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`INVENTARIO_ID`)
)


CREATE TABLE `ITEM` (
  `ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_CODIGO` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ITEM_NOMBRE` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `ITEM_PRECIO_COMPRA` double NOT NULL,
  `ITEM_PRECIO_VENTA` double NOT NULL,
  `ITEM_UNIDADES` double DEFAULT NULL,
  `LABORATORIO_ID` int(11) NOT NULL,
  `PROVEEDOR_ID` int(11) NOT NULL,
  `ITEM_TIPO_ID` int(11) NOT NULL,
  `ITEM_CATEGORIA_ID` int(11) NOT NULL,
  `ITEM_ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ITEM_CATEGORIA` (
  `ITEM_CATEGORIA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_CATEGORIA_NOMBRE` varchar(180) NOT NULL,
  `ITEM_CATEGORIA_ESTADO` varchar(25) NOT NULL,
  PRIMARY KEY (`ITEM_CATEGORIA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `ITEM_TIPO` (
  `ITEM_TIPO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_TIPO_NOMBRE` varchar(50) NOT NULL,
  `ITEM_TIPO_ESTADO` varchar(25) NOT NULL,
  PRIMARY KEY (`ITEM_TIPO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=latin1;

CREATE TABLE `LABORATORIO` (
  `LABORATORIO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LABORATORIO_NOMBRE` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `LABORATORIO_ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`LABORATORIO_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=127 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `PROVEEDOR` (
  `PROVEEDOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROVEEDOR_RUC` varchar(12) NOT NULL,
  `PROVEEDOR_NOMBRE` varchar(180) NOT NULL,
  `PROVEEDOR_DIRECCION` varchar(250) NOT NULL,
  `PROVEEDOR_TELEFONO` varchar(12) DEFAULT NULL,
  `PROVEEDOR_EMAIL` varchar(50) DEFAULT NULL,
  `PROVEEDOR_ESTADO` varchar(25) NOT NULL,
  PRIMARY KEY (`PROVEEDOR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=126 DEFAULT CHARSET=latin1;

CREATE TABLE `SALIDA` (
  `SALIDA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `INVENTARIO_ID` int(11) NOT NULL,
  `SALIDA_PRECIO_COMPRA` double NOT NULL,
  `SALIDA_PRECIO` double NOT NULL,
  `SALIDA_CANTIDAD` int(11) NOT NULL,
  `SALIDA_FECHA` datetime NOT NULL,
  `SALIDA_TIPO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `USUARIO_ID` int(11) NOT NULL,
  `SALIDA_ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `SALIDA_FECHA_CREACION` datetime NOT NULL,
  PRIMARY KEY (`SALIDA_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `USUARIO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `PASSWORD` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `TOKEN` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TIPO_ID` int(11) NOT NULL,
  `EMPLEADO_ID` int(11) NOT NULL,
  `ESTADO` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `USUARIO_TIPO` (
  `USUARIO_TIPO_ID` int(11) NOT NULL,
  `USUARIO_TIPO_NOMBRE` varchar(25) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
