CREATE  TABLE USER (
ID INT NOT NULL PRIMARY KEY auto_increment,
PERFIL VARCHAR(150) NOT NULL,
USUARIO VARCHAR(50) NOT NULL unique,
PASSWORD VARCHAR(30) NOT NULL,
NOMBRES VARCHAR(150) NOT NULL,
TOKEN VARCHAR(150) NOT NULL,
ESTADO VARCHAR(25) not null)

CREATE TABLE CLIENTE(
CLIENTE_ID INT NOT NULL PRIMARY KEY auto_increment,
CLIENTE_NOMBRE VARCHAR(180) NOT NULL,
CLIENTE_DIRECCION VARCHAR(250) NOT NULL,
CLIENTE_DNI VARCHAR(8) default NULL UNIQUE,
CLIENTE_RUC VARCHAR(12) default NULL UNIQUE,
CLIENTE_TELEFONO VARCHAR(12) default NULL,
CLIENTE_ESTADO VARCHAR(12) default NULL
)
select *from CLIENTE

CREATE TABLE PROVEEDOR(
PROVEEDOR_ID INT NOT NULL PRIMARY KEY auto_increment,
PROVEEDOR_RUC VARCHAR(12) NOT NULL,
PROVEEDOR_NOMBRE VARCHAR(180) NOT NULL,
PROVEEDOR_DIRECCION VARCHAR(250) NOT NULL,
PROVEEDOR_TELEFONO VARCHAR(12) default NULL,
PROVEEDOR_EMAIL VARCHAR(50) default NULL,
PROVEEDOR_ESTADO VARCHAR(25) not null)

create TABLE ITEM_CATEGORIA(
ITEM_CATEGORIA_ID INT NOT NULL PRIMARY KEY auto_increment,
ITEM_CATEGORIA_NOMBRE VARCHAR(180) NOT NULL,
ITEM_CATEGORIA_ESTADO VARCHAR(25) not null)
SELECT *FROM ITEM_CATEGORIA

SELECT *FROM ITEM
CREATE TABLE ITEM(
ITEM_ID INT NOT NULL PRIMARY KEY auto_increment,
ITEM_CODIGO VARCHAR(50) NOT NULL UNIQUE,
ITEM_NOMBRE VARCHAR(50) NOT NULL,
ITEM_PRECIO_COMPRA double NOT NULL,
ITEM_PRECIO_VENTA double NOT NULL,
ITEM_UNIDADES double NOT NULL,
PROVEEDOR_ID INT NOT NULL,
ITEM_TIPO_ID INT NOT NULL,
ITEM_CATEGORIA_ID INT NOT NULL,
ITEM_ESTADO VARCHAR(25) not null)

CREATE TABLE ITEM_TIPO(
ITEM_TIPO_ID INT NOT NULL PRIMARY KEY auto_increment,
ITEM_TIPO_NOMBRE VARCHAR(50) NOT NULL,
ITEM_TIPO_ESTADO VARCHAR(25) not null)


CREATE TABLE INVENTARIO(
INVENTARIO_ID INT NOT NULL PRIMARY KEY auto_increment,
ITEM_ID INT NOT NULL,
INVENTARIO_CODIGO_BARRA VARCHAR(80) DEFAULT NULL,
INVENTARIO_UBICACION VARCHAR(80) DEFAULT NULL,
INVENTARIO_CANTIDAD INT NOT NULL,
INVENTARIO_SALDO INT NOT NULL,
INVENTARIO_FECHA_INGRESO DATETIME NOT NULL,
INVENTARIO_FECHA_FABRICACION DATE NOT NULL,
INVENTARIO_FECHA_VENCIMIENTO DATE NOT NULL,
INVENTARIO_ESTADO VARCHAR(25) NOT NULL
)
SELECT *FROM INVENTARIO

select INV.INVENTARIO_ID,INV.ITEM_ID,ITM.ITEM_CODIGO,ITM.ITEM_NOMBRE,
INV.INVENTARIO_CANTIDAD,INV.INVENTARIO_SALDO,
INV.INVENTARIO_FECHA_INGRESO,INV.INVENTARIO_FECHA_FABRICACION,
INV.INVENTARIO_FECHA_VENCIMIENTO,INV.INVENTARIO_ESTADO 
FROM INVENTARIO INV
JOIN ITEM ITM ON ITM.ITEM_ID=INV.ITEM_ID
SELECT INVENTARIO_CANTIDAD,INVENTARIO_SALDO 
FROM INVENTARIO WHERE INVENTARIO_ID=1

SELECT INVENTARIO_CANTIDAD,INVENTARIO_SALDO 
FROM INVENTARIO
WHERE INVENTARIO_ESTADO='ACTIVO' AND INVENTARIO_ID=1


